// Auto-generated by dev-scripts backend-core routes:sync
// Do not edit manually unless you want to override the default handler.
import '@/server/prisma';
export { GET } from '@windrun-huaiin/backend-core/app/api/user/pricing-context/route';
