// Auto-generated by dev-scripts backend-core routes:sync
// Do not edit manually unless you want to override the default handler.
export { POST } from '@windrun-huaiin/backend-core/app/api/user/anonymous/init/route';
